/**
 * Service image resolver (interim, no database changes).
 *
 * Works out which picture to show for a service at display time, using only
 * the service's existing `name` and `category`. Many salons offering the same
 * service therefore share ONE image file on disk.
 *
 * Resolution order (see resolveServiceImageCandidates):
 *   1. Specific image   /service-images/<category>/<slug>.webp   (only if that file exists)
 *   2. Category image   /service-images/_category/<category>.webp
 *   3. Default image    /service-images/_category/default.webp
 *
 * Which specific images exist is listed in `service-images.manifest.json`,
 * regenerated by `node scripts/optimize-service-images.mjs`.
 *
 * Later, when the database ServiceTemplate plan ships, this rule list becomes
 * the seed / backfill matcher and this helper stays as the fallback.
 */
import manifest from "./service-images.manifest.json";

export const SERVICE_IMAGE_ROOT = "/service-images";
export const SERVICE_IMAGE_EXT = "webp";

const KNOWN_CATEGORIES = new Set([
  "hair-styling",
  "nails",
  "hair-removal",
  "eyebrows-eyelashes",
  "facials-skincare",
  "massage",
  "spa-wellness",
  "makeup",
]);

type ServiceImageRule = {
  slug: string; // image file name (without extension)
  category: string;
  keywords: string[]; // matched at the START of a word, e.g. "highlight" matches "Highlights"
};

export const SERVICE_IMAGE_RULES: ServiceImageRule[] = [
  // ── hair-styling ──
  { slug: "haircut", category: "hair-styling", keywords: ["haircut", "hair cut", "trim", "layer cut", "cut"] },
  { slug: "blow-dry", category: "hair-styling", keywords: ["blow dry", "blowdry", "blowout", "blow out"] },
  { slug: "hair-colour", category: "hair-styling", keywords: ["hair colour", "hair color", "colour", "color", "dye"] },
  { slug: "highlights-balayage", category: "hair-styling", keywords: ["highlight", "balayage", "ombre"] },
  { slug: "root-touch-up", category: "hair-styling", keywords: ["root touch", "root", "touch up"] },
  { slug: "hair-spa", category: "hair-styling", keywords: ["hair spa", "hair treatment", "protein", "deep conditioning"] },
  { slug: "keratin-treatment", category: "hair-styling", keywords: ["keratin"] },
  { slug: "rebonding-straightening", category: "hair-styling", keywords: ["rebond", "straighten", "smoothing"] },
  { slug: "perming-curls", category: "hair-styling", keywords: ["perm", "curl"] },
  { slug: "hairstyling-updo", category: "hair-styling", keywords: ["hairstyling", "hair styling", "updo", "hairdo", "styling", "set"] },
  { slug: "hair-braiding", category: "hair-styling", keywords: ["braid", "plait"] },
  { slug: "hair-extensions", category: "hair-styling", keywords: ["hair extension", "extension", "weave"] },
  { slug: "beard-trim-shave", category: "hair-styling", keywords: ["beard", "shave", "moustache", "mustache"] },
  { slug: "head-wash-set", category: "hair-styling", keywords: ["head wash", "shampoo", "wash"] },
  { slug: "hair-oiling", category: "hair-styling", keywords: ["hair oil", "oil"] },
  // ── nails ──
  { slug: "manicure", category: "nails", keywords: ["manicure", "mani"] },
  { slug: "pedicure", category: "nails", keywords: ["pedicure", "pedi"] },
  { slug: "gel-polish", category: "nails", keywords: ["gel polish", "gel nails", "shellac"] },
  { slug: "acrylic-nails", category: "nails", keywords: ["acrylic"] },
  { slug: "gel-extensions", category: "nails", keywords: ["gel extension", "builder gel"] },
  { slug: "nail-art", category: "nails", keywords: ["nail art", "design", "french tip"] },
  { slug: "nail-repair-removal", category: "nails", keywords: ["nail repair", "repair", "removal", "soak off"] },
  { slug: "paraffin-treatment", category: "nails", keywords: ["paraffin", "wax treatment"] },
  // ── hair-removal ──
  { slug: "waxing-full-body", category: "hair-removal", keywords: ["full body wax", "full body"] },
  { slug: "waxing-arms", category: "hair-removal", keywords: ["arm wax", "arms", "arm"] },
  { slug: "waxing-legs", category: "hair-removal", keywords: ["leg wax", "legs", "leg"] },
  { slug: "waxing-underarms", category: "hair-removal", keywords: ["underarm", "armpit"] },
  { slug: "waxing-bikini", category: "hair-removal", keywords: ["bikini", "brazilian"] },
  { slug: "threading-face", category: "hair-removal", keywords: ["face threading", "upper lip", "threading"] },
  { slug: "sugaring", category: "hair-removal", keywords: ["sugar"] },
  { slug: "laser-hair-removal", category: "hair-removal", keywords: ["laser"] },
  // ── eyebrows-eyelashes ──
  { slug: "eyebrow-threading", category: "eyebrows-eyelashes", keywords: ["brow threading", "eyebrow threading"] },
  { slug: "eyebrow-shaping", category: "eyebrows-eyelashes", keywords: ["brow shape", "eyebrow shape", "brow wax", "shaping"] },
  { slug: "eyebrow-tinting", category: "eyebrows-eyelashes", keywords: ["brow tint", "eyebrow tint", "tinting"] },
  { slug: "eyebrow-lamination", category: "eyebrows-eyelashes", keywords: ["brow lamination", "eyebrow lamination", "lamination"] },
  { slug: "lash-extensions", category: "eyebrows-eyelashes", keywords: ["lash extension", "eyelash extension", "lashes", "lash"] },
  { slug: "lash-lift-tint", category: "eyebrows-eyelashes", keywords: ["lash lift", "lash tint"] },
  { slug: "lash-removal", category: "eyebrows-eyelashes", keywords: ["lash removal"] },
  // ── facials-skincare ──
  { slug: "classic-facial", category: "facials-skincare", keywords: ["classic facial", "facial"] },
  { slug: "cleanup", category: "facials-skincare", keywords: ["cleanup", "clean up"] },
  { slug: "deep-cleansing-facial", category: "facials-skincare", keywords: ["deep cleansing", "deep clean"] },
  { slug: "anti-ageing-facial", category: "facials-skincare", keywords: ["anti ageing", "anti aging", "wrinkle"] },
  { slug: "brightening-facial", category: "facials-skincare", keywords: ["brightening", "gold facial", "glow", "whitening"] },
  { slug: "acne-treatment", category: "facials-skincare", keywords: ["acne", "pimple"] },
  { slug: "chemical-peel", category: "facials-skincare", keywords: ["peel"] },
  { slug: "microdermabrasion", category: "facials-skincare", keywords: ["microdermabrasion", "microderm"] },
  { slug: "dermaplaning", category: "facials-skincare", keywords: ["dermaplan"] },
  { slug: "face-mask-treatment", category: "facials-skincare", keywords: ["face mask", "mask"] },
  // ── massage ──
  { slug: "swedish-massage", category: "massage", keywords: ["swedish", "relaxation massage", "full body massage"] },
  { slug: "deep-tissue-massage", category: "massage", keywords: ["deep tissue", "sports massage"] },
  { slug: "aromatherapy-massage", category: "massage", keywords: ["aromatherapy", "aroma"] },
  { slug: "hot-stone-massage", category: "massage", keywords: ["hot stone"] },
  { slug: "ayurvedic-massage", category: "massage", keywords: ["ayurved", "herbal oil massage"] },
  { slug: "head-neck-shoulder-massage", category: "massage", keywords: ["head massage", "indian head", "neck", "shoulder"] },
  { slug: "foot-reflexology", category: "massage", keywords: ["foot massage", "reflexology"] },
  { slug: "back-massage", category: "massage", keywords: ["back massage", "back"] },
  { slug: "couples-massage", category: "massage", keywords: ["couple"] },
  // ── spa-wellness ──
  { slug: "body-scrub", category: "spa-wellness", keywords: ["scrub", "exfoliat"] },
  { slug: "body-wrap", category: "spa-wellness", keywords: ["wrap"] },
  { slug: "shirodhara", category: "spa-wellness", keywords: ["shirodhara"] },
  { slug: "steam-sauna", category: "spa-wellness", keywords: ["steam", "sauna"] },
  { slug: "day-spa-package", category: "spa-wellness", keywords: ["spa package", "package", "day spa", "spa day"] },
  { slug: "herbal-bath", category: "spa-wellness", keywords: ["herbal bath", "bath"] },
  { slug: "body-polishing", category: "spa-wellness", keywords: ["body polish", "polish"] },
  { slug: "detox-treatment", category: "spa-wellness", keywords: ["detox"] },
  // ── makeup ──
  { slug: "bridal-makeup", category: "makeup", keywords: ["bridal makeup", "bride makeup", "bridal"] },
  { slug: "party-makeup", category: "makeup", keywords: ["party", "evening", "occasion"] },
  { slug: "everyday-makeup", category: "makeup", keywords: ["everyday", "natural", "daily"] },
  { slug: "engagement-homecoming-makeup", category: "makeup", keywords: ["engagement", "homecoming"] },
  { slug: "saree-draping", category: "makeup", keywords: ["saree", "sari", "draping"] },
  { slug: "bridal-dressing", category: "makeup", keywords: ["bridal dressing", "dressing"] },
  { slug: "airbrush-makeup", category: "makeup", keywords: ["airbrush"] },
  { slug: "makeup-lesson", category: "makeup", keywords: ["lesson", "class", "tutorial"] },
  { slug: "groom-grooming", category: "makeup", keywords: ["groom", "poruwa"] },
];

const AVAILABLE_SLUGS = new Set<string>(manifest.available);

/** lowercase, punctuation -> spaces, collapsed. "Cut & Blow-dry!" -> "cut blow dry" */
export function normalizeServiceName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

type Match = { rule: ServiceImageRule; position: number; length: number };

function findBestMatch(normalized: string, rules: ServiceImageRule[]): Match | null {
  const haystack = " " + normalized;
  let best: Match | null = null;
  for (const rule of rules) {
    for (const kw of rule.keywords) {
      const idx = haystack.indexOf(" " + kw);
      if (idx === -1) continue;
      // Earliest word in the name wins; on a tie the longer (more specific) keyword wins.
      if (
        !best ||
        idx < best.position ||
        (idx === best.position && kw.length > best.length)
      ) {
        best = { rule, position: idx, length: kw.length };
      }
    }
  }
  return best;
}

/** Best-guess catalog slug for a service, or null if nothing matches. */
export function matchServiceSlug(
  name: string,
  category: string | null | undefined,
): { slug: string; category: string } | null {
  const normalized = normalizeServiceName(name ?? "");
  if (!normalized) return null;

  // 1) Same category first (most accurate).
  if (category && KNOWN_CATEGORIES.has(category)) {
    const inCategory = findBestMatch(
      normalized,
      SERVICE_IMAGE_RULES.filter((r) => r.category === category),
    );
    if (inCategory) return { slug: inCategory.rule.slug, category: inCategory.rule.category };
  }

  // 2) Any category (handles missing / wrong category).
  const anywhere = findBestMatch(normalized, SERVICE_IMAGE_RULES);
  return anywhere ? { slug: anywhere.rule.slug, category: anywhere.rule.category } : null;
}

function specificPath(category: string, slug: string): string {
  return `${SERVICE_IMAGE_ROOT}/${category}/${slug}.${SERVICE_IMAGE_EXT}`;
}

function categoryPath(category: string): string {
  return `${SERVICE_IMAGE_ROOT}/_category/${category}.${SERVICE_IMAGE_EXT}`;
}

const DEFAULT_IMAGE = `${SERVICE_IMAGE_ROOT}/_category/default.${SERVICE_IMAGE_EXT}`;

/**
 * Ordered list of image URLs to try, best first. The UI walks this list if an
 * image fails to load, so a missing file never shows a broken picture.
 */
export function resolveServiceImageCandidates(
  name: string,
  category: string | null | undefined,
): string[] {
  const candidates: string[] = [];

  const match = matchServiceSlug(name, category);
  if (match && AVAILABLE_SLUGS.has(match.slug)) {
    candidates.push(specificPath(match.category, match.slug));
  }

  // Prefer the service's own category for the fallback; else the matched one.
  const fallbackCategory =
    category && KNOWN_CATEGORIES.has(category) ? category : match?.category ?? null;
  if (fallbackCategory) candidates.push(categoryPath(fallbackCategory));

  candidates.push(DEFAULT_IMAGE);
  return candidates;
}

/** Single best image URL for a service. */
export function resolveServiceImage(name: string, category: string | null | undefined): string {
  return resolveServiceImageCandidates(name, category)[0];
}
